<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>StArray.Agents.Diagnostics</RootNamespace>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <DevelopmentDependency>true</DevelopmentDependency>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Resources\AnalyzerResources.resx" />
        <EmbeddedResource Include="Resources\AnalyzerResources.resx">
            <LogicalName>StArray.Agents.Diagnostics.Resources.AnalyzerResources.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Remove="Resources\AnalyzerResources.en.resx" />
        <EmbeddedResource Include="Resources\AnalyzerResources.en.resx">
            <LogicalName>StArray.Agents.Diagnostics.Resources.AnalyzerResources.en.resources</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
    </ItemGroup>

</Project>
