using Microsoft.Extensions.AI;
using StArray.Agents.Abstraction;

namespace StArray.Agents.Core;

/// <summary>
/// 提供从所有 <see cref="ITools"/> 实现创建 AIFunction 的工厂。
/// 内置工具由源生成器编译时自动收集；自定义工具通过 <see cref="AddTools{T}(T)"/> 在运行时注册。
/// Built-in tools are auto-collected at compile-time by source generator;
/// custom tools are registered at runtime via <see cref="AddTools{T}(T)"/>.
/// </summary>
public static partial class FunctionFactory
{
    private static readonly Dictionary<string, ITools> _registeredTools = new();
    private static readonly Lock _lock = new();

    /// <summary>
    /// 注册自定义工具集。可多次调用，重复注册会覆盖。
    /// Registers a custom toolset. Can be called multiple times; duplicate registration overwrites.
    /// </summary>
    public static void AddTools<T>(T tools) where T : ITools
    {
        var key = typeof(T).FullName ?? typeof(T).Name;
        lock (_lock)
        {
            _registeredTools[key] = tools;
        }
    }

    /// <summary>
    /// 注册自定义工具集（使用指定键名）。可多次调用，重复注册会覆盖。
    /// Registers a custom toolset with a specified key. Can be called multiple times; duplicate registration overwrites.
    /// </summary>
    public static void AddTools<T>(string key, T tools) where T : ITools
    {
        lock (_lock)
        {
            _registeredTools[key] = tools;
        }
    }

    /// <summary>
    /// 移除指定工具集。返回是否成功移除。
    /// Removes the specified toolset. Returns whether removal was successful.
    /// </summary>
    public static bool RemoveTools<T>() where T : ITools
    {
        var key = typeof(T).FullName ?? typeof(T).Name;
        lock (_lock)
        {
            return _registeredTools.Remove(key);
        }
    }

    /// <summary>
    /// 清空所有注册的自定义工具。
    /// Clears all registered custom tools.
    /// </summary>
    public static void ClearCustomTools()
    {
        lock (_lock)
        {
            _registeredTools.Clear();
        }
    }

    /// <summary>
    /// 获取所有已注册的自定义工具（不包含内置工具）。
    /// Gets all registered custom tools (does not include built-in tools).
    /// </summary>
    public static IReadOnlyDictionary<string, ITools> GetCustomTools()
    {
        lock (_lock)
        {
            return _registeredTools.ToDictionary(kv => kv.Key, kv => kv.Value);
        }
    }

    /// <summary>
    /// 按类型获取已注册的自定义工具集实例，未注册时返回 default。
    /// Gets the registered custom toolset instance by type; returns default if not registered.
    /// </summary>
    public static T? GetCustomTools<T>() where T : ITools
    {
        var key = typeof(T).FullName ?? typeof(T).Name;
        lock (_lock)
        {
            return _registeredTools.TryGetValue(key, out var tools) ? (T)tools : default;
        }
    }

    /// <summary>
    /// 获取所有工具函数：内置工具 + 用户通过 <see cref="AddTools{T}(T)"/> 注册的自定义工具。
    /// 实现由源生成器生成。 / Implementation is generated by source generator.
    /// </summary>
    public static partial IEnumerable<AIFunction> GetAllFunctions();

    /// <summary>
    /// 由源生成器实现：返回所有内置 <see cref="ITools"/> 实现的 AIFunction 列表。
    /// Implemented by source generator: returns AIFunction list of all built-in <see cref="ITools"/> implementations.
    /// </summary>
    private static partial List<AIFunction> GetBuiltInFunctions();
}